### ISSUE TITLE
Setting the width to outer div

### ISSUE THREAD

**Issue by hjelmeir** [Rick83600/material-ui-textfield-icon#1]
Hello,
I love this wrapper. Only request is you allow me to change the width of the text field. Right now you set it to `256px` or full-width. I would love to set my own width via the style prop.

`<div style={Object.assign({},this.styles.main, props.style}>`

**Comment by Rick83600** [comment]
Of course I will change that :)

**Comment by Rick83600** [comment]
If you want to do a PR you can too

**Comment by Rick83600** [comment]
Ok, you can update to 0.2.2, tell me if it's good for you.
