### ISSUE TITLE
onClick , ubuntu firefox v60.0.2

### ISSUE THREAD

**Issue by GitDema** [Rick83600/material-ui-textfield-icon#2]
does not work onClick event for Ubuntu Firefox v60.0.2

@Rick83600 , can you help, please ?

![ff](https://user-images.githubusercontent.com/8056071/41381170-7feba4f4-6f6f-11e8-8c5a-c1c473f23bd4.png)

**Comment by Rick83600** [comment]
Thanks for your issue I'll test that ! :)

**Comment by GitDema** [comment]
Hey @Rick83600 .
Is there progress? )

**Comment by Rick83600** [comment]
Sorry for late answer, I just test on firefox 64 and the event onClick work great.

Any progress ?

**Comment by GitDema** [comment]
> Sorry for late answer, I just test on firefox 64 and the event onClick work great.
> 
> Any progress ?

strange does not work for me = (
