### ISSUE TITLE
tabindex

### ISSUE THREAD

**Issue by GitDema** [Rick83600/material-ui-textfield-icon#3]
### Hi there, I can't deactivate tab focus for `TextFieldIcon`

When I press the tab key I focus on the icon, and already the next tab key on the input field.
I tried to use `tabindex="-1"`, but it didn't help

Can you help , please @Rick83600

**Comment by Rick83600** [comment]
Hey,

You want to disabled focus on icon and textField or just on icon ?

**Comment by GitDema** [comment]
@Rick83600 Hi, I want to disabled focus on icon or set focus to the textField, and then to the icon

**Comment by Rick83600** [comment]
You have tried to do ?

```javascript
<TextFieldIcon
  hintText='My textField'
  icon={<Money />}
  iconProps={{
    tabIndex: -1
  }}
/>
```

It work well in my storybook :)

**Comment by GitDema** [comment]
@Rick83600, Thank you so much
